### ISSUE TITLE
Last fixes for EDA methods

### ISSUE THREAD

**Issue by Mr-Geekman** [etna-team/etna#11]
<a href="https://github.com/alex-hse-repository"><img src="https://avatars.githubusercontent.com/u/55380696?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alex-hse-repository](https://github.com/alex-hse-repository)**
_Thursday Jun 02, 2022 at 15:46 GMT_
_Originally opened as https://github.com/tinkoff-ai/etna/issues/729_

----

### 🚀 Feature Request

Last fixes for EDA methods

### Motivation

Make our EDA methods better

### Proposal

1. Now `plot_time_series_with_change_points` does not work with NaNs in the middle of the series, try to fix it somehow or throw the appropriate exception
2. Add parameter `segments: Optional[List[str]] = None` to our methods in outliers folder. Method `plot_anomalies` has such parameter, however we can't find anomalies only in specific segments
3. Drop unnecessary segments and all columns except target in `plot_trend` before fitting the trend transforms. This aims to reduce the time/memory
4. Add the title to all the plots without the title. This might be done this way [link](https://github.com/tinkoff-ai/etna/blob/d85c7f0797b5e82fa412ba6d3e2f8c4c2f6e5f9d/etna/analysis/eda_utils.py#L147)

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by d-a-bunin** [comment]
This bug doesn't reproduce here:
```python
import numpy as np

import matplotlib.pyplot as plt

from etna.analysis import plot_trend
from etna.datasets import TSDataset, generate_ar_df
from etna.transforms import LinearTrendTransform


def main():
    df = generate_ar_df(periods=30, n_segments=3, start_time="2020-01-01", freq="D")
    df.loc[df.index[5:7], "target"] = np.NaN
    ts = TSDataset(df=df, freq="D")

    transform = LinearTrendTransform(in_column="target")
    plot_trend(ts=ts, trend_transform=transform)

    plt.savefig("plot_trend.png", bbox_inches="tight")


if __name__ == "__main__":
    main()
```

But it can be reproduced here:
```python
import numpy as np

import matplotlib.pyplot as plt

from etna.analysis import plot_trend
from etna.datasets import TSDataset, generate_ar_df
from etna.transforms import STLTransform


def main():
    df = generate_ar_df(periods=30, n_segments=3, start_time="2020-01-01", freq="D")
    df.loc[df.index[5:7], "target"] = np.NaN
    ts = TSDataset(df=df, freq="D")

    transform = STLTransform(in_column="target", period=7)
    plot_trend(ts=ts, trend_transform=transform)

    plt.savefig("plot_trend.png", bbox_inches="tight")


if __name__ == "__main__":
    main()
```

with stack trace:
```
Traceback (most recent call last):
  File "/Users/d.a.bunin/Library/Application Support/JetBrains/PyCharmCE2022.2/scratches/issue-11.py", line 23, in <module>
    main()
  File "/Users/d.a.bunin/Library/Application Support/JetBrains/PyCharmCE2022.2/scratches/issue-11.py", line 17, in main
    plot_trend(ts=ts, trend_transform=transform)
  File "/Users/d.a.bunin/Documents/etna/etna/analysis/decomposition/plots.py", line 75, in plot_trend
    df_detrend = [transform.fit_transform(deepcopy(ts)).to_pandas() for transform in trend_transform]
  File "/Users/d.a.bunin/Documents/etna/etna/analysis/decomposition/plots.py", line 75, in <listcomp>
    df_detrend = [transform.fit_transform(deepcopy(ts)).to_pandas() for transform in trend_transform]
  File "/Users/d.a.bunin/Documents/etna/etna/transforms/base.py", line 146, in fit_transform
    return self.fit(ts=ts).transform(ts=ts)
  File "/Users/d.a.bunin/Documents/etna/etna/transforms/base.py", line 91, in fit
    self._fit(df=df)
  File "/Users/d.a.bunin/Documents/etna/etna/transforms/base.py", line 353, in _fit
    self.segment_transforms[segment].fit(df[segment])
  File "/Users/d.a.bunin/Documents/etna/etna/transforms/decomposition/stl.py", line 106, in fit
    raise ValueError("The input column contains NaNs in the middle of the series! Try to use the imputer.")
ValueError: The input column contains NaNs in the middle of the series! Try to use the imputer.
```

It looks like it isn't a matter of `plot_trend`, but a matter of transforms. Probably, this issue should be closed.

**Comment by d-a-bunin** [comment]
I can' reproduce an error, it works fine:
```python
import numpy as np

import matplotlib.pyplot as plt

from etna.analysis import plot_time_series_with_change_points
from etna.datasets import TSDataset, generate_ar_df


def main():
    df = generate_ar_df(periods=30, n_segments=3, start_time="2020-01-01", freq="D")
    df.loc[df.index[5:7], "target"] = np.NaN
    ts = TSDataset(df=df, freq="D")

    change_points = {
        "segment_0": [ts.index[10]],
        "segment_1": [ts.index[17]],
        "segment_2": [],
    }
    plot_time_series_with_change_points(ts=ts, change_points=change_points)

    plt.savefig("plot_time_series_with_change_points.png", bbox_inches="tight")


if __name__ == "__main__":
    main()
```
