### ISSUE TITLE
[BUG] to_dict and get_from_params not works correctly with function parameters

### ISSUE THREAD

**Issue by martins0n** [etna-team/etna#270]
### 🐛 Bug Report

get_from_params  change types of function params

### Expected behavior

`transform.to_dict()` should return the same dict in the end as before 

### How To Reproduce

```
from hydra_slayer import  get_from_params


conf = {'in_column': 'target',
   'window_size': 15,
   'distance_coef': 3,
   'n_neighbors': 3,
   'distance_func': {'_target_': 'etna.analysis.outliers.density_outliers.absolute_difference_distance'},
   '_target_': 'etna.transforms.outliers.point_outliers.DensityOutliersTransform'}


transform = get_from_params(**conf)

transform.to_dict()
```

### Environment

2.4.0 etna
python 3.9

### Checklist

- [X] Bug appears at the latest library version

**Comment by egoriyaa** [comment]
For `hydra-slayer==0.5.0` and `etna==2.10` it looks like


```
from hydra_slayer import  get_from_params


conf = {'in_column': 'target',
   'window_size': 15,
   'distance_coef': 3,
   'n_neighbors': 3,
   'distance_func': {'_target_': 'etna.analysis.outliers.density_outliers.absolute_difference_distance'},
   '_target_': 'etna.transforms.outliers.point_outliers.DensityOutliersTransform'}


transform = get_from_params(**conf)

conf_new = transform.to_dict()
transform = get_from_params(**conf_new)
```

```
/Users/e.a.baturin/etna/etna/core/mixins.py:85: UserWarning: Some of external objects in input parameters could be not written in dict
  warnings.warn("Some of external objects in input parameters could be not written in dict")
/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/functional.py:39: UserWarning: No signature found for `<class 'functools.partial'>`, *args and **kwargs arguments cannot be extracted
  warnings.warn(
Traceback (most recent call last):
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/functional.py", line 120, in _get_instance
    instance = metafactory_factory(factory=factory, args=args, kwargs=kwargs)
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/factory.py", line 83, in metafactory_factory
    return meta_factory(factory, args=args, kwargs=kwargs)
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/factory.py", line 160, in default_meta_factory
    obj = call_meta_factory(factory, args, kwargs)
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/factory.py", line 105, in call_meta_factory
    return factory(*args, **kwargs)
TypeError: type 'partial' takes at least one argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/e.a.baturin/etna/etna/file2.py", line 15, in <module>
    transform = get_from_params(**conf_new)
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/functional.py", line 251, in get_from_params
    instance, _ = _recursive_get_from_params(
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/functional.py", line 221, in _recursive_get_from_params
    params[key], vars_dict = _recursive_get_from_params(
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/functional.py", line 226, in _recursive_get_from_params
    instance, vars_dict = _get_from_params(params=params, vars_dict=vars_dict, **common_params)
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/functional.py", line 182, in _get_from_params
    obj = _get_instance(
  File "/Users/e.a.baturin/Library/Caches/pypoetry/virtualenvs/etna-yJQui467-py3.10/lib/python3.10/site-packages/hydra_slayer/functional.py", line 123, in _get_instance
    raise RuntimeError(f"Factory '{name}' call failed: args={args} kwargs={kwargs}") from e
RuntimeError: Factory 'functools.partial' call failed: args=() kwargs={}
```
